/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Bhajan {
  'id' : bigint,
  'title' : string,
  'lyrics' : string,
  'language' : { 'hindi' : null } |
    { 'english' : null },
}
export interface Chalisa {
  'id' : bigint,
  'title' : string,
  'meaning' : string,
  'fullText' : string,
}
export interface CommunityPost {
  'id' : bigint,
  'status' : CommunityPostStatus,
  'content' : string,
  'video' : [] | [ExternalBlob],
  'author' : Principal,
  'likes' : bigint,
  'fileAttachment' : [] | [FileAttachment],
  'timestamp' : bigint,
  'reports' : bigint,
  'image' : [] | [ExternalBlob],
  'comments' : bigint,
  'deityTag' : [] | [string],
}
export type CommunityPostStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface DharmaQuote {
  'id' : bigint,
  'author' : string,
  'englishText' : string,
  'hindiText' : string,
}
export type ExternalBlob = Uint8Array;
export interface Festival {
  'date' : string,
  'name' : string,
  'description' : string,
}
export interface FileAttachment { 'blob' : ExternalBlob, 'filename' : string }
export interface JapCounter {
  'streak' : bigint,
  'lastReset' : bigint,
  'mala' : bigint,
  'lastActiveDate' : bigint,
  'lifetime' : bigint,
  'tempCount' : bigint,
  'daily' : bigint,
}
export interface Katha {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'audioBlob' : [] | [ExternalBlob],
  'englishText' : string,
  'category' : KathaCategory,
  'hindiText' : string,
  'deity' : string,
}
export type KathaCategory = { 'vrat' : null } |
  { 'puranik' : null };
export interface KrishnaLeela { 'id' : bigint, 'hindiText' : string }
export type Mantra = { 'saiRam' : null } |
  { 'hareKrishna' : null } |
  { 'mahamrityunjayaMantra' : null } |
  { 'omMantra' : null } |
  { 'jaiShreeRamNamJap' : null } |
  { 'sitaram' : null } |
  { 'gayatriMantra' : null } |
  { 'omNamahShivaya' : null } |
  { 'radhaNamJap' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'selectedMantra' : Mantra, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vrat {
  'id' : bigint,
  'date' : string,
  'name' : string,
  'description' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBhajan' : ActorMethod<
    [string, string, { 'hindi' : null } | { 'english' : null }],
    bigint
  >,
  'addChalisa' : ActorMethod<[string, string, string], bigint>,
  'addDharmaQuote' : ActorMethod<[bigint, string, string, string], undefined>,
  'addKatha' : ActorMethod<
    [
      string,
      KathaCategory,
      string,
      string,
      string,
      Array<string>,
      [] | [ExternalBlob],
    ],
    bigint
  >,
  'addVrat' : ActorMethod<[string, string, string], bigint>,
  'approveCommunityPost' : ActorMethod<[bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCommunityPost' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      [] | [FileAttachment],
    ],
    bigint
  >,
  'deleteBhajan' : ActorMethod<[bigint], boolean>,
  'deleteChalisa' : ActorMethod<[bigint], boolean>,
  'deleteCommunityPost' : ActorMethod<[bigint], boolean>,
  'deleteDharmaQuote' : ActorMethod<[bigint], boolean>,
  'deleteKatha' : ActorMethod<[bigint], boolean>,
  'deleteVrat' : ActorMethod<[bigint], boolean>,
  'getAllBhajans' : ActorMethod<[], Array<Bhajan>>,
  'getAllChalisa' : ActorMethod<[], Array<Chalisa>>,
  'getAllCommunityPosts' : ActorMethod<[], Array<CommunityPost>>,
  'getAllKathayen' : ActorMethod<[], Array<Katha>>,
  'getAllVrats' : ActorMethod<[], Array<Vrat>>,
  'getBhajan' : ActorMethod<[bigint], [] | [Bhajan]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChalisa' : ActorMethod<[bigint], [] | [Chalisa]>,
  'getCommunityPosts' : ActorMethod<[], Array<CommunityPost>>,
  'getDharmaQuoteOfDay' : ActorMethod<[], [] | [DharmaQuote]>,
  'getFestivals' : ActorMethod<[], Array<Festival>>,
  'getJapLeaderboard' : ActorMethod<[], Array<JapCounter>>,
  'getJapStats' : ActorMethod<[], JapCounter>,
  'getKatha' : ActorMethod<[bigint], [] | [Katha]>,
  'getKathayen' : ActorMethod<[], Array<Katha>>,
  'getKrishnaLeelaStory' : ActorMethod<[], KrishnaLeela>,
  'getPendingCommunityPosts' : ActorMethod<[], Array<CommunityPost>>,
  'getUserMantra' : ActorMethod<[], Mantra>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementJap' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'likeCommunityPost' : ActorMethod<[bigint], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listKathayenByCategory' : ActorMethod<[KathaCategory], Array<Katha>>,
  'rejectCommunityPost' : ActorMethod<[bigint], boolean>,
  'reportCommunityPost' : ActorMethod<[bigint], boolean>,
  'requestApproval' : ActorMethod<[], undefined>,
  'resetJapStats' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchKathayenByDeity' : ActorMethod<[string], Array<Katha>>,
  'searchKathayenByTitle' : ActorMethod<[string], Array<Katha>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateBhajan' : ActorMethod<
    [bigint, string, string, { 'hindi' : null } | { 'english' : null }],
    boolean
  >,
  'updateChalisa' : ActorMethod<[bigint, string, string, string], boolean>,
  'updateDharmaQuote' : ActorMethod<[bigint, string, string, string], boolean>,
  'updateKatha' : ActorMethod<
    [
      bigint,
      string,
      KathaCategory,
      string,
      string,
      string,
      Array<string>,
      [] | [ExternalBlob],
    ],
    boolean
  >,
  'updateVrat' : ActorMethod<[bigint, string, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];