/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Katha {
    id: bigint;
    status: KathaApprovalStatus;
    title: string;
    createdAt: bigint;
    tags: Array<string>;
    englishText: string;
    category: KathaCategory;
    hindiText: string;
    deity: string;
}
export interface DharmaQuote {
    id: bigint;
    author: string;
    englishText: string;
    hindiText: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Festival {
    date: string;
    name: string;
    description: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface JapStatsInternal {
    lastReset: bigint;
    lifetime: bigint;
    daily: bigint;
    weekly: bigint;
}
export interface CommunityPost {
    id: bigint;
    status: KathaApprovalStatus;
    content: string;
    author: Principal;
    likes: bigint;
    timestamp: bigint;
    reports: bigint;
    comments: bigint;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface JapStats {
    lifetime: bigint;
    daily: bigint;
    weekly: bigint;
}
export interface KrishnaLeela {
    id: bigint;
    hindiText: string;
}
export interface UserProfile {
    selectedMantra: Mantra;
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum KathaApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum KathaCategory {
    vrat = "vrat",
    puranik = "puranik"
}
export enum Mantra {
    saiRam = "saiRam",
    hareKrishna = "hareKrishna",
    mahamrityunjayaMantra = "mahamrityunjayaMantra",
    omMantra = "omMantra",
    jaiShreeRamNamJap = "jaiShreeRamNamJap",
    sitaram = "sitaram",
    gayatriMantra = "gayatriMantra",
    omNamahShivaya = "omNamahShivaya",
    radhaNamJap = "radhaNamJap"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAarti(id: bigint, name: string, hindiText: string, englishText: string): Promise<void>;
    addDharmaQuote(id: bigint, englishText: string, hindiText: string, author: string): Promise<void>;
    addKatha(title: string, category: KathaCategory, deity: string, hindiText: string, englishText: string, tags: Array<string>): Promise<bigint>;
    approveCommunityPost(postId: bigint): Promise<boolean>;
    approveKatha(kathaId: bigint): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCommunityPost(content: string): Promise<bigint>;
    getAllCommunityPosts(): Promise<Array<CommunityPost>>;
    getAllKathayen(): Promise<Array<Katha>>;
    getApprovedCommunityPosts(): Promise<Array<CommunityPost>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDharmaQuoteOfDay(): Promise<DharmaQuote | null>;
    getFestivals(): Promise<Array<Festival>>;
    getJapLeaderboard(): Promise<Array<JapStats>>;
    getJapStats(): Promise<JapStatsInternal>;
    getKatha(id: bigint): Promise<Katha | null>;
    getKrishnaLeelaStory(): Promise<KrishnaLeela>;
    getUserMantra(): Promise<Mantra>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    incrementJap(count: bigint): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    likeCommunityPost(postId: bigint): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listKathayenByCategory(category: KathaCategory): Promise<Array<Katha>>;
    rejectCommunityPost(postId: bigint): Promise<boolean>;
    reportCommunityPost(postId: bigint): Promise<boolean>;
    requestApproval(): Promise<void>;
    resetJapStats(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchKathayenByDeity(deity: string): Promise<Array<Katha>>;
    searchKathayenByTitle(search: string): Promise<Array<Katha>>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setUserProfile(profile: UserProfile): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, CommunityPost as _CommunityPost, DharmaQuote as _DharmaQuote, Katha as _Katha, KathaApprovalStatus as _KathaApprovalStatus, KathaCategory as _KathaCategory, Mantra as _Mantra, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAarti(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAarti(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAarti(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addDharmaQuote(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDharmaQuote(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDharmaQuote(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addKatha(arg0: string, arg1: KathaCategory, arg2: string, arg3: string, arg4: string, arg5: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addKatha(arg0, to_candid_KathaCategory_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addKatha(arg0, to_candid_KathaCategory_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async approveCommunityPost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveCommunityPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveCommunityPost(arg0);
            return result;
        }
    }
    async approveKatha(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveKatha(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveKatha(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCommunityPost(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCommunityPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCommunityPost(arg0);
            return result;
        }
    }
    async getAllCommunityPosts(): Promise<Array<CommunityPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCommunityPosts();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCommunityPosts();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllKathayen(): Promise<Array<Katha>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKathayen();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKathayen();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedCommunityPosts(): Promise<Array<CommunityPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedCommunityPosts();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedCommunityPosts();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDharmaQuoteOfDay(): Promise<DharmaQuote | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDharmaQuoteOfDay();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDharmaQuoteOfDay();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFestivals(): Promise<Array<Festival>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFestivals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFestivals();
            return result;
        }
    }
    async getJapLeaderboard(): Promise<Array<JapStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJapLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJapLeaderboard();
            return result;
        }
    }
    async getJapStats(): Promise<JapStatsInternal> {
        if (this.processError) {
            try {
                const result = await this.actor.getJapStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJapStats();
            return result;
        }
    }
    async getKatha(arg0: bigint): Promise<Katha | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKatha(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKatha(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKrishnaLeelaStory(): Promise<KrishnaLeela> {
        if (this.processError) {
            try {
                const result = await this.actor.getKrishnaLeelaStory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKrishnaLeelaStory();
            return result;
        }
    }
    async getUserMantra(): Promise<Mantra> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMantra();
                return from_candid_Mantra_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMantra();
            return from_candid_Mantra_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementJap(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementJap(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementJap(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async likeCommunityPost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likeCommunityPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeCommunityPost(arg0);
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async listKathayenByCategory(arg0: KathaCategory): Promise<Array<Katha>> {
        if (this.processError) {
            try {
                const result = await this.actor.listKathayenByCategory(to_candid_KathaCategory_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listKathayenByCategory(to_candid_KathaCategory_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectCommunityPost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectCommunityPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectCommunityPost(arg0);
            return result;
        }
    }
    async reportCommunityPost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.reportCommunityPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportCommunityPost(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async resetJapStats(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetJapStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetJapStats();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchKathayenByDeity(arg0: string): Promise<Array<Katha>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchKathayenByDeity(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchKathayenByDeity(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchKathayenByTitle(arg0: string): Promise<Array<Katha>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchKathayenByTitle(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchKathayenByTitle(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n39(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n39(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_CommunityPost_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommunityPost): CommunityPost {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_KathaApprovalStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KathaApprovalStatus): KathaApprovalStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_KathaCategory_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KathaCategory): KathaCategory {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Katha_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Katha): Katha {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Mantra_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mantra): Mantra {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DharmaQuote]): DharmaQuote | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Katha]): Katha | null {
    return value.length === 0 ? null : from_candid_Katha_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    content: string;
    author: Principal;
    likes: bigint;
    timestamp: bigint;
    reports: bigint;
    comments: bigint;
}): {
    id: bigint;
    status: KathaApprovalStatus;
    content: string;
    author: Principal;
    likes: bigint;
    timestamp: bigint;
    reports: bigint;
    comments: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n15(_uploadFile, _downloadFile, value.status),
        content: value.content,
        author: value.author,
        likes: value.likes,
        timestamp: value.timestamp,
        reports: value.reports,
        comments: value.comments
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _KathaApprovalStatus;
    title: string;
    createdAt: bigint;
    tags: Array<string>;
    englishText: string;
    category: _KathaCategory;
    hindiText: string;
    deity: string;
}): {
    id: bigint;
    status: KathaApprovalStatus;
    title: string;
    createdAt: bigint;
    tags: Array<string>;
    englishText: string;
    category: KathaCategory;
    hindiText: string;
    deity: string;
} {
    return {
        id: value.id,
        status: from_candid_KathaApprovalStatus_n19(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        tags: value.tags,
        englishText: value.englishText,
        category: from_candid_KathaCategory_n20(_uploadFile, _downloadFile, value.category),
        hindiText: value.hindiText,
        deity: value.deity
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    selectedMantra: _Mantra;
    name: string;
}): {
    selectedMantra: Mantra;
    name: string;
} {
    return {
        selectedMantra: from_candid_Mantra_n25(_uploadFile, _downloadFile, value.selectedMantra),
        name: value.name
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n34(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): KathaApprovalStatus {
    return "pending" in value ? KathaApprovalStatus.pending : "approved" in value ? KathaApprovalStatus.approved : "rejected" in value ? KathaApprovalStatus.rejected : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vrat: null;
} | {
    puranik: null;
}): KathaCategory {
    return "vrat" in value ? KathaCategory.vrat : "puranik" in value ? KathaCategory.puranik : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    saiRam: null;
} | {
    hareKrishna: null;
} | {
    mahamrityunjayaMantra: null;
} | {
    omMantra: null;
} | {
    jaiShreeRamNamJap: null;
} | {
    sitaram: null;
} | {
    gayatriMantra: null;
} | {
    omNamahShivaya: null;
} | {
    radhaNamJap: null;
}): Mantra {
    return "saiRam" in value ? Mantra.saiRam : "hareKrishna" in value ? Mantra.hareKrishna : "mahamrityunjayaMantra" in value ? Mantra.mahamrityunjayaMantra : "omMantra" in value ? Mantra.omMantra : "jaiShreeRamNamJap" in value ? Mantra.jaiShreeRamNamJap : "sitaram" in value ? Mantra.sitaram : "gayatriMantra" in value ? Mantra.gayatriMantra : "omNamahShivaya" in value ? Mantra.omNamahShivaya : "radhaNamJap" in value ? Mantra.radhaNamJap : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommunityPost>): Array<CommunityPost> {
    return value.map((x)=>from_candid_CommunityPost_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Katha>): Array<Katha> {
    return value.map((x)=>from_candid_Katha_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n32(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_KathaCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KathaCategory): _KathaCategory {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Mantra_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mantra): _Mantra {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    selectedMantra: Mantra;
    name: string;
}): {
    selectedMantra: _Mantra;
    name: string;
} {
    return {
        selectedMantra: to_candid_Mantra_n37(_uploadFile, _downloadFile, value.selectedMantra),
        name: value.name
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mantra): {
    saiRam: null;
} | {
    hareKrishna: null;
} | {
    mahamrityunjayaMantra: null;
} | {
    omMantra: null;
} | {
    jaiShreeRamNamJap: null;
} | {
    sitaram: null;
} | {
    gayatriMantra: null;
} | {
    omNamahShivaya: null;
} | {
    radhaNamJap: null;
} {
    return value == Mantra.saiRam ? {
        saiRam: null
    } : value == Mantra.hareKrishna ? {
        hareKrishna: null
    } : value == Mantra.mahamrityunjayaMantra ? {
        mahamrityunjayaMantra: null
    } : value == Mantra.omMantra ? {
        omMantra: null
    } : value == Mantra.jaiShreeRamNamJap ? {
        jaiShreeRamNamJap: null
    } : value == Mantra.sitaram ? {
        sitaram: null
    } : value == Mantra.gayatriMantra ? {
        gayatriMantra: null
    } : value == Mantra.omNamahShivaya ? {
        omNamahShivaya: null
    } : value == Mantra.radhaNamJap ? {
        radhaNamJap: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KathaApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == KathaApprovalStatus.pending ? {
        pending: null
    } : value == KathaApprovalStatus.approved ? {
        approved: null
    } : value == KathaApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KathaCategory): {
    vrat: null;
} | {
    puranik: null;
} {
    return value == KathaCategory.vrat ? {
        vrat: null
    } : value == KathaCategory.puranik ? {
        puranik: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
