/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface DharmaQuote {
  'id' : bigint,
  'author' : string,
  'englishText' : string,
  'hindiText' : string,
}
export interface Festival {
  'date' : string,
  'name' : string,
  'description' : string,
}
export interface JapStats {
  'lifetime' : bigint,
  'daily' : bigint,
  'weekly' : bigint,
}
export interface JapStatsInternal {
  'lastReset' : bigint,
  'lifetime' : bigint,
  'daily' : bigint,
  'weekly' : bigint,
}
export interface Katha {
  'id' : bigint,
  'status' : KathaApprovalStatus,
  'title' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'englishText' : string,
  'category' : KathaCategory,
  'hindiText' : string,
  'deity' : string,
}
export type KathaApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type KathaCategory = { 'vrat' : null } |
  { 'puranik' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAarti' : ActorMethod<[bigint, string, string, string], undefined>,
  'addDharmaQuote' : ActorMethod<[bigint, string, string, string], undefined>,
  'addKatha' : ActorMethod<
    [string, KathaCategory, string, string, string, Array<string>],
    bigint
  >,
  'addPanchang' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    undefined
  >,
  'approveKatha' : ActorMethod<[bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllKathayen' : ActorMethod<[], Array<Katha>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDharmaQuoteOfDay' : ActorMethod<[], [] | [DharmaQuote]>,
  'getFestivals' : ActorMethod<[], Array<Festival>>,
  'getJapLeaderboard' : ActorMethod<[], Array<JapStats>>,
  'getJapStats' : ActorMethod<[], JapStatsInternal>,
  'getKatha' : ActorMethod<[bigint], [] | [Katha]>,
  'getPanchang' : ActorMethod<
    [bigint],
    { 'tithi' : [] | [string], 'muhurat' : [] | [string] }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementJap' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listKathayenByCategory' : ActorMethod<[KathaCategory], Array<Katha>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchKathayenByDeity' : ActorMethod<[string], Array<Katha>>,
  'searchKathayenByTitle' : ActorMethod<[string], Array<Katha>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];