/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const KathaCategory = IDL.Variant({
  'vrat' : IDL.Null,
  'puranik' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileAttachment = IDL.Record({
  'blob' : ExternalBlob,
  'filename' : IDL.Text,
});
export const Bhajan = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'lyrics' : IDL.Text,
  'language' : IDL.Variant({ 'hindi' : IDL.Null, 'english' : IDL.Null }),
});
export const Chalisa = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'meaning' : IDL.Text,
  'fullText' : IDL.Text,
});
export const CommunityPostStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const CommunityPost = IDL.Record({
  'id' : IDL.Nat,
  'status' : CommunityPostStatus,
  'content' : IDL.Text,
  'video' : IDL.Opt(ExternalBlob),
  'author' : IDL.Principal,
  'likes' : IDL.Nat,
  'fileAttachment' : IDL.Opt(FileAttachment),
  'timestamp' : IDL.Nat,
  'reports' : IDL.Nat,
  'image' : IDL.Opt(ExternalBlob),
  'comments' : IDL.Nat,
  'deityTag' : IDL.Opt(IDL.Text),
});
export const KathaApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Katha = IDL.Record({
  'id' : IDL.Nat,
  'status' : KathaApprovalStatus,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'englishText' : IDL.Text,
  'category' : KathaCategory,
  'hindiText' : IDL.Text,
  'deity' : IDL.Text,
});
export const Vrat = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Mantra = IDL.Variant({
  'saiRam' : IDL.Null,
  'hareKrishna' : IDL.Null,
  'mahamrityunjayaMantra' : IDL.Null,
  'omMantra' : IDL.Null,
  'jaiShreeRamNamJap' : IDL.Null,
  'sitaram' : IDL.Null,
  'gayatriMantra' : IDL.Null,
  'omNamahShivaya' : IDL.Null,
  'radhaNamJap' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'selectedMantra' : Mantra,
  'name' : IDL.Text,
});
export const DharmaQuote = IDL.Record({
  'id' : IDL.Nat,
  'author' : IDL.Text,
  'englishText' : IDL.Text,
  'hindiText' : IDL.Text,
});
export const Festival = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const JapCounter = IDL.Record({
  'streak' : IDL.Nat,
  'lastReset' : IDL.Int,
  'mala' : IDL.Nat,
  'lastActiveDate' : IDL.Int,
  'lifetime' : IDL.Nat,
  'tempCount' : IDL.Nat,
  'daily' : IDL.Nat,
});
export const KrishnaLeela = IDL.Record({
  'id' : IDL.Nat,
  'hindiText' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBhajan' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Variant({ 'hindi' : IDL.Null, 'english' : IDL.Null }),
      ],
      [IDL.Nat],
      [],
    ),
  'addChalisa' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addDharmaQuote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addKatha' : IDL.Func(
      [
        IDL.Text,
        KathaCategory,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'addVrat' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'approveCommunityPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'approveKatha' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCommunityPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(FileAttachment),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteBhajan' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteChalisa' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCommunityPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteDharmaQuote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteVrat' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllBhajans' : IDL.Func([], [IDL.Vec(Bhajan)], ['query']),
  'getAllChalisa' : IDL.Func([], [IDL.Vec(Chalisa)], ['query']),
  'getAllCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
  'getAllKathayen' : IDL.Func([], [IDL.Vec(Katha)], ['query']),
  'getAllVrats' : IDL.Func([], [IDL.Vec(Vrat)], ['query']),
  'getApprovedCommunityPosts' : IDL.Func(
      [],
      [IDL.Vec(CommunityPost)],
      ['query'],
    ),
  'getBhajan' : IDL.Func([IDL.Nat], [IDL.Opt(Bhajan)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChalisa' : IDL.Func([IDL.Nat], [IDL.Opt(Chalisa)], ['query']),
  'getDharmaQuoteOfDay' : IDL.Func([], [IDL.Opt(DharmaQuote)], ['query']),
  'getFestivals' : IDL.Func([], [IDL.Vec(Festival)], ['query']),
  'getJapLeaderboard' : IDL.Func([], [IDL.Vec(JapCounter)], ['query']),
  'getJapStats' : IDL.Func([], [JapCounter], ['query']),
  'getKatha' : IDL.Func([IDL.Nat], [IDL.Opt(Katha)], ['query']),
  'getKrishnaLeelaStory' : IDL.Func([], [KrishnaLeela], ['query']),
  'getUserMantra' : IDL.Func([], [Mantra], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementJap' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'likeCommunityPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listKathayenByCategory' : IDL.Func(
      [KathaCategory],
      [IDL.Vec(Katha)],
      ['query'],
    ),
  'rejectCommunityPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'reportCommunityPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'requestApproval' : IDL.Func([], [], []),
  'resetJapStats' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile, IDL.Text], [], []),
  'searchKathayenByDeity' : IDL.Func([IDL.Text], [IDL.Vec(Katha)], ['query']),
  'searchKathayenByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Katha)], ['query']),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setUserProfile' : IDL.Func([UserProfile, IDL.Text], [], []),
  'updateBhajan' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Variant({ 'hindi' : IDL.Null, 'english' : IDL.Null }),
      ],
      [IDL.Bool],
      [],
    ),
  'updateChalisa' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateDharmaQuote' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateVrat' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const KathaCategory = IDL.Variant({
    'vrat' : IDL.Null,
    'puranik' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileAttachment = IDL.Record({
    'blob' : ExternalBlob,
    'filename' : IDL.Text,
  });
  const Bhajan = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'lyrics' : IDL.Text,
    'language' : IDL.Variant({ 'hindi' : IDL.Null, 'english' : IDL.Null }),
  });
  const Chalisa = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'meaning' : IDL.Text,
    'fullText' : IDL.Text,
  });
  const CommunityPostStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const CommunityPost = IDL.Record({
    'id' : IDL.Nat,
    'status' : CommunityPostStatus,
    'content' : IDL.Text,
    'video' : IDL.Opt(ExternalBlob),
    'author' : IDL.Principal,
    'likes' : IDL.Nat,
    'fileAttachment' : IDL.Opt(FileAttachment),
    'timestamp' : IDL.Nat,
    'reports' : IDL.Nat,
    'image' : IDL.Opt(ExternalBlob),
    'comments' : IDL.Nat,
    'deityTag' : IDL.Opt(IDL.Text),
  });
  const KathaApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Katha = IDL.Record({
    'id' : IDL.Nat,
    'status' : KathaApprovalStatus,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'englishText' : IDL.Text,
    'category' : KathaCategory,
    'hindiText' : IDL.Text,
    'deity' : IDL.Text,
  });
  const Vrat = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Mantra = IDL.Variant({
    'saiRam' : IDL.Null,
    'hareKrishna' : IDL.Null,
    'mahamrityunjayaMantra' : IDL.Null,
    'omMantra' : IDL.Null,
    'jaiShreeRamNamJap' : IDL.Null,
    'sitaram' : IDL.Null,
    'gayatriMantra' : IDL.Null,
    'omNamahShivaya' : IDL.Null,
    'radhaNamJap' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'selectedMantra' : Mantra,
    'name' : IDL.Text,
  });
  const DharmaQuote = IDL.Record({
    'id' : IDL.Nat,
    'author' : IDL.Text,
    'englishText' : IDL.Text,
    'hindiText' : IDL.Text,
  });
  const Festival = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const JapCounter = IDL.Record({
    'streak' : IDL.Nat,
    'lastReset' : IDL.Int,
    'mala' : IDL.Nat,
    'lastActiveDate' : IDL.Int,
    'lifetime' : IDL.Nat,
    'tempCount' : IDL.Nat,
    'daily' : IDL.Nat,
  });
  const KrishnaLeela = IDL.Record({ 'id' : IDL.Nat, 'hindiText' : IDL.Text });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBhajan' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Variant({ 'hindi' : IDL.Null, 'english' : IDL.Null }),
        ],
        [IDL.Nat],
        [],
      ),
    'addChalisa' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addDharmaQuote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addKatha' : IDL.Func(
        [
          IDL.Text,
          KathaCategory,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'addVrat' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'approveCommunityPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'approveKatha' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCommunityPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(FileAttachment),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteBhajan' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteChalisa' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCommunityPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteDharmaQuote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteVrat' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllBhajans' : IDL.Func([], [IDL.Vec(Bhajan)], ['query']),
    'getAllChalisa' : IDL.Func([], [IDL.Vec(Chalisa)], ['query']),
    'getAllCommunityPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
    'getAllKathayen' : IDL.Func([], [IDL.Vec(Katha)], ['query']),
    'getAllVrats' : IDL.Func([], [IDL.Vec(Vrat)], ['query']),
    'getApprovedCommunityPosts' : IDL.Func(
        [],
        [IDL.Vec(CommunityPost)],
        ['query'],
      ),
    'getBhajan' : IDL.Func([IDL.Nat], [IDL.Opt(Bhajan)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChalisa' : IDL.Func([IDL.Nat], [IDL.Opt(Chalisa)], ['query']),
    'getDharmaQuoteOfDay' : IDL.Func([], [IDL.Opt(DharmaQuote)], ['query']),
    'getFestivals' : IDL.Func([], [IDL.Vec(Festival)], ['query']),
    'getJapLeaderboard' : IDL.Func([], [IDL.Vec(JapCounter)], ['query']),
    'getJapStats' : IDL.Func([], [JapCounter], ['query']),
    'getKatha' : IDL.Func([IDL.Nat], [IDL.Opt(Katha)], ['query']),
    'getKrishnaLeelaStory' : IDL.Func([], [KrishnaLeela], ['query']),
    'getUserMantra' : IDL.Func([], [Mantra], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementJap' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'likeCommunityPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listKathayenByCategory' : IDL.Func(
        [KathaCategory],
        [IDL.Vec(Katha)],
        ['query'],
      ),
    'rejectCommunityPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'reportCommunityPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'requestApproval' : IDL.Func([], [], []),
    'resetJapStats' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile, IDL.Text], [], []),
    'searchKathayenByDeity' : IDL.Func([IDL.Text], [IDL.Vec(Katha)], ['query']),
    'searchKathayenByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Katha)], ['query']),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setUserProfile' : IDL.Func([UserProfile, IDL.Text], [], []),
    'updateBhajan' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Variant({ 'hindi' : IDL.Null, 'english' : IDL.Null }),
        ],
        [IDL.Bool],
        [],
      ),
    'updateChalisa' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateDharmaQuote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateVrat' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };