/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    selectedMantra: Mantra;
    name: string;
}
export interface Katha {
    id: bigint;
    title: string;
    createdAt: bigint;
    tags: Array<string>;
    audioBlob?: ExternalBlob;
    englishText: string;
    category: KathaCategory;
    hindiText: string;
    deity: string;
}
export interface DharmaQuote {
    id: bigint;
    author: string;
    englishText: string;
    hindiText: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Festival {
    date: string;
    name: string;
    description: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Bhajan {
    id: bigint;
    title: string;
    lyrics: string;
    language: Variant_hindi_english;
}
export interface CommunityPost {
    id: bigint;
    status: CommunityPostStatus;
    content: string;
    video?: ExternalBlob;
    author: Principal;
    likes: bigint;
    fileAttachment?: FileAttachment;
    timestamp: bigint;
    reports: bigint;
    image?: ExternalBlob;
    comments: bigint;
    deityTag?: string;
}
export interface JapCounter {
    streak: bigint;
    lastReset: bigint;
    mala: bigint;
    lastActiveDate: bigint;
    lifetime: bigint;
    tempCount: bigint;
    daily: bigint;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface FileAttachment {
    blob: ExternalBlob;
    filename: string;
}
export interface Chalisa {
    id: bigint;
    title: string;
    meaning: string;
    fullText: string;
}
export interface KrishnaLeela {
    id: bigint;
    hindiText: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Vrat {
    id: bigint;
    date: string;
    name: string;
    description: string;
}
export enum CommunityPostStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum KathaCategory {
    vrat = "vrat",
    puranik = "puranik"
}
export enum Mantra {
    saiRam = "saiRam",
    hareKrishna = "hareKrishna",
    mahamrityunjayaMantra = "mahamrityunjayaMantra",
    omMantra = "omMantra",
    jaiShreeRamNamJap = "jaiShreeRamNamJap",
    sitaram = "sitaram",
    gayatriMantra = "gayatriMantra",
    omNamahShivaya = "omNamahShivaya",
    radhaNamJap = "radhaNamJap"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_hindi_english {
    hindi = "hindi",
    english = "english"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBhajan(title: string, lyrics: string, language: Variant_hindi_english): Promise<bigint>;
    addChalisa(title: string, fullText: string, meaning: string): Promise<bigint>;
    addDharmaQuote(id: bigint, englishText: string, hindiText: string, author: string): Promise<void>;
    addKatha(title: string, category: KathaCategory, deity: string, hindiText: string, englishText: string, tags: Array<string>, audioBlob: ExternalBlob | null): Promise<bigint>;
    addVrat(name: string, date: string, description: string): Promise<bigint>;
    approveCommunityPost(postId: bigint): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCommunityPost(content: string, deityTag: string | null, image: ExternalBlob | null, video: ExternalBlob | null, fileAttachment: FileAttachment | null): Promise<bigint>;
    deleteBhajan(id: bigint): Promise<boolean>;
    deleteChalisa(id: bigint): Promise<boolean>;
    deleteCommunityPost(postId: bigint): Promise<boolean>;
    deleteDharmaQuote(id: bigint): Promise<boolean>;
    deleteKatha(id: bigint): Promise<boolean>;
    deleteVrat(id: bigint): Promise<boolean>;
    getAllBhajans(): Promise<Array<Bhajan>>;
    getAllChalisa(): Promise<Array<Chalisa>>;
    getAllCommunityPosts(): Promise<Array<CommunityPost>>;
    getAllKathayen(): Promise<Array<Katha>>;
    getAllVrats(): Promise<Array<Vrat>>;
    getBhajan(id: bigint): Promise<Bhajan | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChalisa(id: bigint): Promise<Chalisa | null>;
    getCommunityPosts(): Promise<Array<CommunityPost>>;
    getDharmaQuoteOfDay(): Promise<DharmaQuote | null>;
    getFestivals(): Promise<Array<Festival>>;
    getJapLeaderboard(): Promise<Array<JapCounter>>;
    getJapStats(): Promise<JapCounter>;
    getKatha(id: bigint): Promise<Katha | null>;
    getKathayen(): Promise<Array<Katha>>;
    getKrishnaLeelaStory(): Promise<KrishnaLeela>;
    getPendingCommunityPosts(): Promise<Array<CommunityPost>>;
    getUserMantra(): Promise<Mantra>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    incrementJap(count: bigint): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    likeCommunityPost(postId: bigint): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    listKathayenByCategory(category: KathaCategory): Promise<Array<Katha>>;
    rejectCommunityPost(postId: bigint): Promise<boolean>;
    reportCommunityPost(postId: bigint): Promise<boolean>;
    requestApproval(): Promise<void>;
    resetJapStats(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchKathayenByDeity(deity: string): Promise<Array<Katha>>;
    searchKathayenByTitle(search: string): Promise<Array<Katha>>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updateBhajan(id: bigint, title: string, lyrics: string, language: Variant_hindi_english): Promise<boolean>;
    updateChalisa(id: bigint, title: string, fullText: string, meaning: string): Promise<boolean>;
    updateDharmaQuote(id: bigint, englishText: string, hindiText: string, author: string): Promise<boolean>;
    updateKatha(id: bigint, title: string, category: KathaCategory, deity: string, hindiText: string, englishText: string, tags: Array<string>, audioBlob: ExternalBlob | null): Promise<boolean>;
    updateVrat(id: bigint, name: string, date: string, description: string): Promise<boolean>;
}
import type { ApprovalStatus as _ApprovalStatus, Bhajan as _Bhajan, Chalisa as _Chalisa, CommunityPost as _CommunityPost, CommunityPostStatus as _CommunityPostStatus, DharmaQuote as _DharmaQuote, ExternalBlob as _ExternalBlob, FileAttachment as _FileAttachment, Katha as _Katha, KathaCategory as _KathaCategory, Mantra as _Mantra, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBhajan(arg0: string, arg1: string, arg2: Variant_hindi_english): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBhajan(arg0, arg1, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBhajan(arg0, arg1, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addChalisa(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addChalisa(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChalisa(arg0, arg1, arg2);
            return result;
        }
    }
    async addDharmaQuote(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDharmaQuote(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDharmaQuote(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addKatha(arg0: string, arg1: KathaCategory, arg2: string, arg3: string, arg4: string, arg5: Array<string>, arg6: ExternalBlob | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addKatha(arg0, to_candid_KathaCategory_n9(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addKatha(arg0, to_candid_KathaCategory_n9(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async addVrat(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addVrat(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVrat(arg0, arg1, arg2);
            return result;
        }
    }
    async approveCommunityPost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.approveCommunityPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveCommunityPost(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCommunityPost(arg0: string, arg1: string | null, arg2: ExternalBlob | null, arg3: ExternalBlob | null, arg4: FileAttachment | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCommunityPost(arg0, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCommunityPost(arg0, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg3), await to_candid_opt_n16(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deleteBhajan(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBhajan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBhajan(arg0);
            return result;
        }
    }
    async deleteChalisa(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChalisa(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChalisa(arg0);
            return result;
        }
    }
    async deleteCommunityPost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCommunityPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCommunityPost(arg0);
            return result;
        }
    }
    async deleteDharmaQuote(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDharmaQuote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDharmaQuote(arg0);
            return result;
        }
    }
    async deleteKatha(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteKatha(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteKatha(arg0);
            return result;
        }
    }
    async deleteVrat(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVrat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVrat(arg0);
            return result;
        }
    }
    async getAllBhajans(): Promise<Array<Bhajan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBhajans();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBhajans();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllChalisa(): Promise<Array<Chalisa>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllChalisa();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllChalisa();
            return result;
        }
    }
    async getAllCommunityPosts(): Promise<Array<CommunityPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCommunityPosts();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCommunityPosts();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllKathayen(): Promise<Array<Katha>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKathayen();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKathayen();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVrats(): Promise<Array<Vrat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVrats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVrats();
            return result;
        }
    }
    async getBhajan(arg0: bigint): Promise<Bhajan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBhajan(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBhajan(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChalisa(arg0: bigint): Promise<Chalisa | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChalisa(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChalisa(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommunityPosts(): Promise<Array<CommunityPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunityPosts();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunityPosts();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDharmaQuoteOfDay(): Promise<DharmaQuote | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDharmaQuoteOfDay();
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDharmaQuoteOfDay();
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFestivals(): Promise<Array<Festival>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFestivals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFestivals();
            return result;
        }
    }
    async getJapLeaderboard(): Promise<Array<JapCounter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJapLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJapLeaderboard();
            return result;
        }
    }
    async getJapStats(): Promise<JapCounter> {
        if (this.processError) {
            try {
                const result = await this.actor.getJapStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJapStats();
            return result;
        }
    }
    async getKatha(arg0: bigint): Promise<Katha | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKatha(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKatha(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKathayen(): Promise<Array<Katha>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKathayen();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKathayen();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKrishnaLeelaStory(): Promise<KrishnaLeela> {
        if (this.processError) {
            try {
                const result = await this.actor.getKrishnaLeelaStory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKrishnaLeelaStory();
            return result;
        }
    }
    async getPendingCommunityPosts(): Promise<Array<CommunityPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingCommunityPosts();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingCommunityPosts();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserMantra(): Promise<Mantra> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMantra();
                return from_candid_Mantra_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMantra();
            return from_candid_Mantra_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementJap(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementJap(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementJap(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async likeCommunityPost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likeCommunityPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeCommunityPost(arg0);
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listKathayenByCategory(arg0: KathaCategory): Promise<Array<Katha>> {
        if (this.processError) {
            try {
                const result = await this.actor.listKathayenByCategory(to_candid_KathaCategory_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listKathayenByCategory(to_candid_KathaCategory_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectCommunityPost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectCommunityPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectCommunityPost(arg0);
            return result;
        }
    }
    async reportCommunityPost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.reportCommunityPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportCommunityPost(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async resetJapStats(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetJapStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetJapStats();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n54(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n54(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchKathayenByDeity(arg0: string): Promise<Array<Katha>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchKathayenByDeity(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchKathayenByDeity(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchKathayenByTitle(arg0: string): Promise<Array<Katha>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchKathayenByTitle(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchKathayenByTitle(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n58(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n58(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateBhajan(arg0: bigint, arg1: string, arg2: string, arg3: Variant_hindi_english): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBhajan(arg0, arg1, arg2, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBhajan(arg0, arg1, arg2, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateChalisa(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChalisa(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChalisa(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateDharmaQuote(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDharmaQuote(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDharmaQuote(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateKatha(arg0: bigint, arg1: string, arg2: KathaCategory, arg3: string, arg4: string, arg5: string, arg6: Array<string>, arg7: ExternalBlob | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKatha(arg0, arg1, to_candid_KathaCategory_n9(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKatha(arg0, arg1, to_candid_KathaCategory_n9(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, await to_candid_opt_n11(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async updateVrat(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVrat(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVrat(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Bhajan_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bhajan): Bhajan {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_CommunityPostStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommunityPostStatus): CommunityPostStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_CommunityPost_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommunityPost): Promise<CommunityPost> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FileAttachment_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileAttachment): Promise<FileAttachment> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_KathaCategory_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KathaCategory): KathaCategory {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_Katha_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Katha): Promise<Katha> {
    return await from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Mantra_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mantra): Mantra {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileAttachment]): Promise<FileAttachment | null> {
    return value.length === 0 ? null : await from_candid_FileAttachment_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Bhajan]): Bhajan | null {
    return value.length === 0 ? null : from_candid_Bhajan_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Chalisa]): Chalisa | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DharmaQuote]): DharmaQuote | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Katha]): Promise<Katha | null> {
    return value.length === 0 ? null : await from_candid_Katha_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    lyrics: string;
    language: {
        hindi: null;
    } | {
        english: null;
    };
}): {
    id: bigint;
    title: string;
    lyrics: string;
    language: Variant_hindi_english;
} {
    return {
        id: value.id,
        title: value.title,
        lyrics: value.lyrics,
        language: from_candid_variant_n22(_uploadFile, _downloadFile, value.language)
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CommunityPostStatus;
    content: string;
    video: [] | [_ExternalBlob];
    author: Principal;
    likes: bigint;
    fileAttachment: [] | [_FileAttachment];
    timestamp: bigint;
    reports: bigint;
    image: [] | [_ExternalBlob];
    comments: bigint;
    deityTag: [] | [string];
}): Promise<{
    id: bigint;
    status: CommunityPostStatus;
    content: string;
    video?: ExternalBlob;
    author: Principal;
    likes: bigint;
    fileAttachment?: FileAttachment;
    timestamp: bigint;
    reports: bigint;
    image?: ExternalBlob;
    comments: bigint;
    deityTag?: string;
}> {
    return {
        id: value.id,
        status: from_candid_CommunityPostStatus_n26(_uploadFile, _downloadFile, value.status),
        content: value.content,
        video: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.video)),
        author: value.author,
        likes: value.likes,
        fileAttachment: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.fileAttachment)),
        timestamp: value.timestamp,
        reports: value.reports,
        image: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.image)),
        comments: value.comments,
        deityTag: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.deityTag))
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    filename: string;
}): Promise<{
    blob: ExternalBlob;
    filename: string;
}> {
    return {
        blob: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.blob),
        filename: value.filename
    };
}
async function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    createdAt: bigint;
    tags: Array<string>;
    audioBlob: [] | [_ExternalBlob];
    englishText: string;
    category: _KathaCategory;
    hindiText: string;
    deity: string;
}): Promise<{
    id: bigint;
    title: string;
    createdAt: bigint;
    tags: Array<string>;
    audioBlob?: ExternalBlob;
    englishText: string;
    category: KathaCategory;
    hindiText: string;
    deity: string;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        tags: value.tags,
        audioBlob: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.audioBlob)),
        englishText: value.englishText,
        category: from_candid_KathaCategory_n37(_uploadFile, _downloadFile, value.category),
        hindiText: value.hindiText,
        deity: value.deity
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    selectedMantra: _Mantra;
    name: string;
}): {
    selectedMantra: Mantra;
    name: string;
} {
    return {
        selectedMantra: from_candid_Mantra_n43(_uploadFile, _downloadFile, value.selectedMantra),
        name: value.name
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n53(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hindi: null;
} | {
    english: null;
}): Variant_hindi_english {
    return "hindi" in value ? Variant_hindi_english.hindi : "english" in value ? Variant_hindi_english.english : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): CommunityPostStatus {
    return "pending" in value ? CommunityPostStatus.pending : "approved" in value ? CommunityPostStatus.approved : "rejected" in value ? CommunityPostStatus.rejected : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vrat: null;
} | {
    puranik: null;
}): KathaCategory {
    return "vrat" in value ? KathaCategory.vrat : "puranik" in value ? KathaCategory.puranik : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    saiRam: null;
} | {
    hareKrishna: null;
} | {
    mahamrityunjayaMantra: null;
} | {
    omMantra: null;
} | {
    jaiShreeRamNamJap: null;
} | {
    sitaram: null;
} | {
    gayatriMantra: null;
} | {
    omNamahShivaya: null;
} | {
    radhaNamJap: null;
}): Mantra {
    return "saiRam" in value ? Mantra.saiRam : "hareKrishna" in value ? Mantra.hareKrishna : "mahamrityunjayaMantra" in value ? Mantra.mahamrityunjayaMantra : "omMantra" in value ? Mantra.omMantra : "jaiShreeRamNamJap" in value ? Mantra.jaiShreeRamNamJap : "sitaram" in value ? Mantra.sitaram : "gayatriMantra" in value ? Mantra.gayatriMantra : "omNamahShivaya" in value ? Mantra.omNamahShivaya : "radhaNamJap" in value ? Mantra.radhaNamJap : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bhajan>): Array<Bhajan> {
    return value.map((x)=>from_candid_Bhajan_n20(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommunityPost>): Promise<Array<CommunityPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CommunityPost_n24(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Katha>): Promise<Array<Katha>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Katha_n35(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n51(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n59(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_FileAttachment_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileAttachment): Promise<_FileAttachment> {
    return await to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_KathaCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KathaCategory): _KathaCategory {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Mantra_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mantra): _Mantra {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileAttachment | null): Promise<[] | [_FileAttachment]> {
    return value === null ? candid_none() : candid_some(await to_candid_FileAttachment_n17(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
    filename: string;
}): Promise<{
    blob: _ExternalBlob;
    filename: string;
}> {
    return {
        blob: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.blob),
        filename: value.filename
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    selectedMantra: Mantra;
    name: string;
}): {
    selectedMantra: _Mantra;
    name: string;
} {
    return {
        selectedMantra: to_candid_Mantra_n56(_uploadFile, _downloadFile, value.selectedMantra),
        name: value.name
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KathaCategory): {
    vrat: null;
} | {
    puranik: null;
} {
    return value == KathaCategory.vrat ? {
        vrat: null
    } : value == KathaCategory.puranik ? {
        puranik: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mantra): {
    saiRam: null;
} | {
    hareKrishna: null;
} | {
    mahamrityunjayaMantra: null;
} | {
    omMantra: null;
} | {
    jaiShreeRamNamJap: null;
} | {
    sitaram: null;
} | {
    gayatriMantra: null;
} | {
    omNamahShivaya: null;
} | {
    radhaNamJap: null;
} {
    return value == Mantra.saiRam ? {
        saiRam: null
    } : value == Mantra.hareKrishna ? {
        hareKrishna: null
    } : value == Mantra.mahamrityunjayaMantra ? {
        mahamrityunjayaMantra: null
    } : value == Mantra.omMantra ? {
        omMantra: null
    } : value == Mantra.jaiShreeRamNamJap ? {
        jaiShreeRamNamJap: null
    } : value == Mantra.sitaram ? {
        sitaram: null
    } : value == Mantra.gayatriMantra ? {
        gayatriMantra: null
    } : value == Mantra.omNamahShivaya ? {
        omNamahShivaya: null
    } : value == Mantra.radhaNamJap ? {
        radhaNamJap: null
    } : value;
}
function to_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CommunityPostStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == CommunityPostStatus.pending ? {
        pending: null
    } : value == CommunityPostStatus.approved ? {
        approved: null
    } : value == CommunityPostStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_hindi_english): {
    hindi: null;
} | {
    english: null;
} {
    return value == Variant_hindi_english.hindi ? {
        hindi: null
    } : value == Variant_hindi_english.english ? {
        english: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
